create table RSV_ADM_CONF
(
  RAC_ADL_KBN      integer     not null,
  RAC_ADL_YEAR     integer,
  RAC_ADL_MONTH    integer,
  RAC_HOUR_DIV     integer,
  RAC_AUID         integer     not null,
  RAC_ADATE        timestamp  not null,
  RAC_EUID         integer     not null,
  RAC_EDATE        timestamp  not null,
  RAC_DTM_KBN      integer     not null default 0,
  RAC_DTM_FR       integer     not null default 9,
  RAC_DTM_TO       integer     not null default 18,
  RAC_INI_EDIT_KBN integer     not null default 0,
  RAC_INI_EDIT     integer     not null default 0,
  RAC_SMAIL_SEND_KBN integer     not null default 0,
  RAC_SMAIL_SEND     integer     not null default 0,
  RAC_AM_FR_H integer not null default 9,
  RAC_AM_FR_M integer not null default 0,
  RAC_AM_TO_H integer not null default 12,
  RAC_AM_TO_M integer not null default 0,
  RAC_PM_FR_H integer not null default 13,
  RAC_PM_FR_M integer not null default 0,
  RAC_PM_TO_H integer not null default 18,
  RAC_PM_TO_M integer not null default 0,
  RAC_ALL_FR_H integer not null default 9,
  RAC_ALL_FR_M integer not null default 0,
  RAC_ALL_TO_H integer not null default 18,
  RAC_ALL_TO_M integer not null default 0,
  RAC_INI_PERIOD_KBN integer not null default 0,
  RAC_INI_FR_H integer not null default 9,
  RAC_INI_FR_M integer not null default 0,
  RAC_INI_TO_H integer not null default 18,
  RAC_INI_TO_M integer not null default 0,
  RAC_INI_PUBLIC_KBN integer default 0 not null,
  RAC_INI_PUBLIC integer default 0 not null
);